name: Update Built-in Modules

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - .node-version
      - .github/workflows/update-builtins.yml
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  update-builtins:
    name: Update Node.js Built-in Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: true
          token: ${{ secrets.OXC_BOT_PAT }}

      - uses: oxc-project/setup-node@8958a8e040102244b619c4a94fccb657a44b1c21 # v1.0.6

      - uses: oxc-project/setup-rust@c8224157c0bf235aabc633e8cd50d344f087a7de # v1.0.12
        with:
          components: rustfmt

      - run: cargo run -p update_builtins

      - run: cargo fmt

      - run: cargo test

      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          commit_message: "chore: update built-in modules for Node.js ${{ steps.node-version.outputs.version }} [skip ci]"
          file_pattern: src/lib.rs
